# Generated by Django 5.1.7 on 2025-03-23 09:36

import customer.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.UUID('ab78139e-1f86-4e99-a1c8-4e38b3cbea26'), editable=False)),
                ('vat_number', models.CharField(default=customer.models.generate_vat_number, max_length=9, unique=True)),
            ],
        ),
    ]
