# Generated by Django 5.1.7 on 2025-03-23 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.UUIDField(default=uuid.UUID('0376f5ca-4fee-4740-929f-0c6eed24182f'), editable=False),
        ),
    ]
